language: go
go:
    - 1.6
    - tip
matrix:
    allow_failures:
        - go: tip
env:
    - TODO_DB_NAME=todo
install:
    - go get -u github.com/golang/lint/golint
before_script:
    - psql -c 'create database todo;' -U postgres
    - psql -U postgres todo < db/tables.sql
script:
    - make test
