language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - tip
matrix:
    allow_failures:
        - go: tip
before_script:
    - cp db/test.json db/database.json
    - psql -c 'create database todo;' -U postgres
    - ./script/db -e test < db/tables.sql
install:
    - go get github.com/stretchr/testify/assert
    - go get -d ./... && go test -i ./... && go build -v ./...
